# SITE CONFIGURATION
title: Yasha Iravantchi # your site title
author: Yasha Iravantchi # You :P
description: > # Meta description of Homepage
  Yasha Iravantchi's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yasha.xyz" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Yasha Iravantchi
  links:
    - https://twitter.com/yashasir
    - https://www.facebook.com/yashasir
    - https://github.com/yashairavantchi

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Academics', link: '/academics'}

tagline: >
  Ph.D. Student, Future Interfaces Group, SmaSH Lab, Carnegie Mellon University

hero_img: posts/pittsburgh.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ysi [at] cs [dot] cmu [dot] edu # email for form submission

twitter_username: yashasir # replace with your_twitter_username or comment to remove link from footer
github_username:  yashairavantchi # replace with your_github_username or comment to remove link from footer
instagram_username: yashasir # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: ## # to enable comments replace with your_disqus_shortname

google_tag_manager: UA-83031036-1 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-83031036-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics