# Site settings
title: Yasha Iravantchi
email: yasha@seas.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Yasha Iravantchi's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yasha.xyz" # the base hostname & protocol for your site
twitter_username: yashasir
github_username:  yashairavantchi

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Design Specialist at Harvard SEAS"
excerpt_separator: "<!--more-->"

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'


defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

sass:
  style: compressed
