# Site settings
title: Yasha Iravantchi
email: yasha@seas.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Yasha Iravantchi's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yasha.xyz" # the base hostname & protocol for your site
twitter_username: yashasir
github_username:  yashairavantchi

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Design Specialist at Harvard SEAS"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""